<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add                                 _6c91be</name>
   <tag></tag>
   <elementGuidId>1de6a0b0-289b-4161-9385-fb231f1e97fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-pill.btn-air-primary.btn-outline-primary.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3871b07-612a-4b46-9e76-391e3ac5b40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfae5eab-e85b-42f3-a7df-1855cfa638e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-pill btn-air-primary btn-outline-primary text-white</value>
      <webElementGuid>816b30b3-9cbf-44af-a93b-90d49c7b51fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>c49bbdf8-e4e0-4b11-9e92-bf781c3ef92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalAdd</value>
      <webElementGuid>7acf0387-1489-43de-88ee-d8ba9bf75d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add
                                                            Branch</value>
      <webElementGuid>231ebcdd-38aa-4de2-b9eb-a755c4d0bd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbranch&quot;)/div[@class=&quot;table-responsive resp-branch&quot;]/div[@class=&quot;btn-popup pull-right&quot;]/button[@class=&quot;btn btn-primary btn-pill btn-air-primary btn-outline-primary text-white&quot;]</value>
      <webElementGuid>b499a92e-94d0-4fdd-8727-4777d49d542f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>6d23ccf2-7a78-4038-bb92-243b03b5a9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbranch']/div/div/button</value>
      <webElementGuid>bdae9870-34eb-49f9-908f-bfe874318010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>1e8b4944-c660-4480-a861-89c43bf39967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Add
                                                            Branch' or . = ' Add
                                                            Branch')]</value>
      <webElementGuid>300f33fe-2eac-465d-9e99-60afd1ae980a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
