<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_instanceCode</name>
   <tag></tag>
   <elementGuidId>3d33d5f9-f34c-479b-96a3-fc7035b3b721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kodeInstansiAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kodeInstansiAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40a789ec-e7dd-459e-863e-6e00c474cde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d78efcb-643b-4c1d-aecd-d2b78124124c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>60b07924-6f6f-4e02-bf70-d4c744586760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kodeInstansiAdd</value>
      <webElementGuid>4c813761-a841-40f4-82ce-fa1c178a2461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instanceCode</value>
      <webElementGuid>1efac14d-a807-42b5-9b51-8e9acd069e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Instansi</value>
      <webElementGuid>0eb5e664-cb7b-4606-ade3-80c229296b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c53c0fde-ca41-4faf-ae48-cb70523a9097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kodeInstansiAdd&quot;)</value>
      <webElementGuid>f221179d-d2b4-4cca-9714-78798f065aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kodeInstansiAdd']</value>
      <webElementGuid>ac81b453-6f67-4a33-b841-e176617ffbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/input</value>
      <webElementGuid>b55c6669-40cc-47a4-ba42-74f45a30dd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>a50188b4-5fb9-4e38-a4b7-beb6f8caa4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kodeInstansiAdd' and @name = 'instanceCode' and @placeholder = 'Kode Instansi']</value>
      <webElementGuid>fea76ae5-531e-4791-9aac-168b8a30b1b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
