<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>61fa7ee4-6240-4bbb-8cb4-76ca85db4ae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formAdd > div.modal-body > div.form-group > #nameAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='nameAdd'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c598618-624d-402d-9246-caa3725cdee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c9eb865-8894-40b1-bb19-bc1a4114b6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1bd740a2-a17c-40c0-8ca2-ad120a1f0854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameAdd</value>
      <webElementGuid>8b35f101-59fd-45ae-b200-2cc7fa0dcb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>72d1241d-0b58-449c-9db0-e8fc103f198e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>9cc796f1-127f-498f-b271-c0aaa085758b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d0ab06a-e808-4aaf-85f7-019a4592de82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAdd&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/input[@id=&quot;nameAdd&quot;]</value>
      <webElementGuid>3ccbde7b-05f9-4861-a6db-e2b416bc5fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='nameAdd'])[2]</value>
      <webElementGuid>c3fcc9e2-1c1d-41d8-86f6-90915014f4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/input</value>
      <webElementGuid>c694c933-6bf2-49b4-9466-f5b5b1d5d6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div/input</value>
      <webElementGuid>ed226ed3-9d3b-4171-9429-5a53d2c05340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameAdd' and @name = 'name' and @placeholder = 'Name']</value>
      <webElementGuid>cc2f33c5-1808-4929-9d3c-869e3f230520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
