<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_box</name>
   <tag></tag>
   <elementGuidId>ff775a9b-5548-4ce9-a8e7-ba16ffb5c82c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modalAdd&quot;]/span/span/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ce5ee597-0cdb-458b-9444-4125cda6b407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705650168303</value>
      <webElementGuid>12413c24-ebf7-4f89-a993-3dedc3212efd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
