<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selected_user</name>
   <tag></tag>
   <elementGuidId>2236c9c5-4985-418a-b29a-f6be99616d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;select2-picAdd-results&quot;]/li[contains(text(),'Eric - iglo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>54987297-9c85-4f0b-9192-765e82c1d7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705650260402</value>
      <webElementGuid>ebb00f75-14a5-4248-ba0f-7ab7803848c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
