<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_21</name>
   <tag></tag>
   <elementGuidId>68162189-f17a-4d71-ac43-67d8f397ea45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.active.day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6268a677-f6bc-4bf4-84f0-33f367ffea64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active day</value>
      <webElementGuid>c6d0ae8c-31aa-4ef4-87a7-318105cdee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>def61967-9d72-47b0-9b2c-28def1a32395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;datepicker datepicker-dropdown dropdown-menu datepicker-orient-left datepicker-orient-top&quot;]/div[@class=&quot;datepicker-days&quot;]/table[@class=&quot;table-condensed&quot;]/tbody[1]/tr[4]/td[@class=&quot;active day&quot;]</value>
      <webElementGuid>f372d5de-fc97-4a8b-a42d-c9dd7aca4b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]</value>
      <webElementGuid>e3412da3-5a25-4182-9536-24f5cfc04724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '21' or . = '21')]</value>
      <webElementGuid>55bb578d-9078-4bfc-97db-743308f5b2d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
